#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

echo "### pytest:"
${PREFIX}coverage run --source=src -m pytest
${PREFIX}coverage report -m --fail-under 65
echo "### black:"
${PREFIX}black src --check --diff
echo "### flake8:"
${PREFIX}flake8 src
echo "### Radon complexity check:"
${PREFIX}radon cc --min B --total-average src
echo "### Visual Studio maintainability index:"
${PREFIX}radon mi --min B src
echo "### tests done"