name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start the database
        run: docker-compose up -d db
      - name: Migrate the database schema
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build migration
      - name: Test
        run: docker-compose run --no-deps rest scripts/test
      - name: Shutdown database
        if: ${{ always() }}
        run: docker-compose stop db
